=== BrentDouglas/chainlink/chainlink_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cl="http://machinecode.io/xml/ns/chainlink"
           targetNamespace="http://machinecode.io/xml/ns/chainlink"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified"
           version="1.0">
    <xs:annotation>
        <xs:documentation>
            Configuration for a Chainlink deployment.
        </xs:documentation>
    </xs:annotation>

    <xs:element name="chainlink" type="cl:DeploymentType"/>

    <xs:complexType name="ScopeType" abstract="true">
        <xs:annotation>
            <xs:documentation>
                A Chainlink scope.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="job-operator" type="cl:JobOperatorType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="property" type="cl:PropertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DeploymentType">
        <xs:annotation>
            <xs:documentation>
                A Chainlink deployment. Resources declared here will be created for each deployment and will be shared
                by any operators in that deployment.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="cl:ScopeType">
                <xs:attribute name="ref" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            An injectable reference for the DeploymentConfiguration to use to configure this deployment.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="configuration-loaders" type="cl:ListType" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="JobOperatorType">
        <xs:annotation>
            <xs:documentation>
                A JobOperator.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="cl:NamedType">
                <xs:sequence>
                    <xs:element name="property" type="cl:PropertyType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="ref" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>
                            An injectable reference for the JobOperatorConfiguration to use to configure this job operator.
                        </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="class-loader" type="xs:string" use="optional"/>
                <xs:attribute name="transaction-manager" type="xs:string" use="optional"/>
                <xs:attribute name="marshalling" type="xs:string" use="optional"/>
                <xs:attribute name="mbean-server" type="xs:string" use="optional"/>
                <xs:attribute name="repository" type="xs:string" use="optional"/>
                <xs:attribute name="registry" type="xs:string" use="optional"/>
                <xs:attribute name="transport" type="xs:string" use="optional"/>
                <xs:attribute name="executor" type="xs:string" use="optional"/>
                <xs:attribute name="job-loaders" type="cl:ListType" use="optional"/>
                <xs:attribute name="artifact-loaders" type="cl:ListType" use="optional"/>
                <xs:attribute name="securities" type="cl:ListType" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="NamedType">
        <xs:attribute name="name" use="required" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    The name this element may referred to by other elements using this attribute.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="DeclarationType">
        <xs:annotation>
            <xs:documentation>
                A resource that may be used by a JobOperator.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute name="ref" use="required" type="xs:string">
            <xs:annotation>
                <xs:documentation>
                    An injectable reference for either a factory or an artifact.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="PropertyType">
        <xs:attribute name="name" use="required" type="xs:string" />
        <xs:attribute name="value" use="required" type="xs:string" />
    </xs:complexType>

    <xs:simpleType name="ListType">
        <xs:list itemType="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== BrentDouglas/chainlink/server/chainlinkd/cnf/chainlink.xml
<?xml version="1.0" encoding="UTF-8"?>
<chainlink xmlns="http://io.machinecode/xml/ns/chainlink"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://io.machinecode/xml/ns/chainlink http://io.machinecode/xml/ns/chainlink/chainlink_1_0.xsd">

    <job-operator name="default">
        <marshalling name="marshalling" factory="io.machinecode.chainlink.marshalling.jdk.JdkMarshallingFactory"/>
        <mbean-server name="mbean-server" factory="io.machinecode.chainlink.core.management.jmx.PlatformMBeanServerFactory"/>
        <execution-repository name="execution-repository" factory="io.machinecode.chainlink.repository.memory.MemoryExecutionRepositoryFactory"/>
        <registry name="registry" factory="io.machinecode.chainlink.core.registry.LocalRegistryFactory"/>
        <transport name="transport" factory="io.machinecode.chainlink.core.transport.LocalTransportFactory"/>
        <executor name="executor" factory="io.machinecode.chainlink.core.execution.EventedExecutorFactory"/>
    </job-operator>

</chainlink>
